type: BIGCONFIG_FILE
tag_deployments:
- collection:
    name: Operational Checks
    notification_channels:
    - slack: '#de-bigeye-triage'
  deployments:
  - column_selectors:
    - name: moz-fx-data-shared-prod.moz-fx-data-shared-prod.google_ads_derived.fenix_conversion_event_categorization_v1.report_date
    - name: moz-fx-data-shared-prod.moz-fx-data-shared-prod.google_ads_derived.fenix_conversion_event_categorization_v1.first_seen_date
    - name: moz-fx-data-shared-prod.moz-fx-data-shared-prod.google_ads_derived.fenix_conversion_event_categorization_v1.first_week_end_date
    - name: moz-fx-data-shared-prod.moz-fx-data-shared-prod.google_ads_derived.fenix_conversion_event_categorization_v1.client_id
    - name: moz-fx-data-shared-prod.moz-fx-data-shared-prod.google_ads_derived.fenix_conversion_event_categorization_v1.gclid
    - name: moz-fx-data-shared-prod.moz-fx-data-shared-prod.google_ads_derived.fenix_conversion_event_categorization_v1.marketing_card_optin_first_week
    - name: moz-fx-data-shared-prod.moz-fx-data-shared-prod.google_ads_derived.fenix_conversion_event_categorization_v1.active_d0
    - name: moz-fx-data-shared-prod.moz-fx-data-shared-prod.google_ads_derived.fenix_conversion_event_categorization_v1.active_d1
    - name: moz-fx-data-shared-prod.moz-fx-data-shared-prod.google_ads_derived.fenix_conversion_event_categorization_v1.active_d2
    - name: moz-fx-data-shared-prod.moz-fx-data-shared-prod.google_ads_derived.fenix_conversion_event_categorization_v1.active_d3
    - name: moz-fx-data-shared-prod.moz-fx-data-shared-prod.google_ads_derived.fenix_conversion_event_categorization_v1.active_d4
    - name: moz-fx-data-shared-prod.moz-fx-data-shared-prod.google_ads_derived.fenix_conversion_event_categorization_v1.active_d5
    - name: moz-fx-data-shared-prod.moz-fx-data-shared-prod.google_ads_derived.fenix_conversion_event_categorization_v1.active_d6
    - name: moz-fx-data-shared-prod.moz-fx-data-shared-prod.google_ads_derived.fenix_conversion_event_categorization_v1.activation_1
    - name: moz-fx-data-shared-prod.moz-fx-data-shared-prod.google_ads_derived.fenix_conversion_event_categorization_v1.activation_2
    metrics:
    - saved_metric_id: is_not_null
      rct_overrides:
      - report_date
  - column_selectors:
    - name: moz-fx-data-shared-prod.moz-fx-data-shared-prod.google_ads_derived.fenix_conversion_event_categorization_v1.client_id
    metrics:
    - saved_metric_id: is_unique
      rct_overrides:
      - report_date
  - column_selectors:
    - name: moz-fx-data-shared-prod.moz-fx-data-shared-prod.google_ads_derived.fenix_conversion_event_categorization_v1.*
    metrics:
    - saved_metric_id: volume
    - saved_metric_id: freshness
